### ISSUE TITLE
Smalltalk implementation of Travis pretty printer

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#173]
smalltalkCI currently uses a [Python script](https://github.com/hpi-swa/smalltalkCI/blob/master/lib/junit_xml_prettfier.py) which pretty prints the output and adds syntactic sugar for Travis. This can be implemented completely in Smalltalk.

I've already started with this including a new testrunner for smalltalkCI. On Pharo, `HDTestReport` is currently used and GemStone and Squeak use a ported version. The new testrunner is less hacky and supports JUnit XML export and stdout pretty printing.

**Comment by fniephaus** [comment]
@dalehenrich this should also make it easier to avoid flooding the Travis log with the XML. We can even add an option then...

**Comment by fniephaus** [comment]
@dalehenrich have you tried not splitting the `metacello-work` test across two builds? The XML output should not be printed then.

**Comment by dalehenrich** [comment]
@fniephaus  I guess you are talking about generating the pretty output directly as the tests are run instead of dumping xml to disk first? Presumably the only time you'd want to actually generate the xml would be when you are running in Jenkins or the like that is expecting to parse the xml?

**Comment by dalehenrich** [comment]
@fniephaus the original reason for splitting the Metacello builds was to avoid the 30 minute time limit (no 45 minute timeout) and [recently I've fixed the bug that was causing the builds to take so long](https://github.com/dalehenrich/metacello-work/issues/390#issuecomment-230916262). That bugfix came in shortly before the `smalltalk_edge` feature "stopped working" --- the build time dropped to about 20 minutes so I wasn't panicked that I lost  `smalltalk_edge`.

It still is true that I can go over the log limit for travis if I have a number of error  tests during the combined run, since we end up with two copies of the stack - one in the xml and one in the pretty print ... Eliminating the xml altogether would change the threshold for lost information so for now I'm going to stick with the split builds since I prefer not to lose information when tests fail ...

**Comment by fniephaus** [comment]
AFAIK you can still see more than 10k lines when downloading the log, but then it won't be colorized and it's another click. Still not 100% what you/we want.
Some of our student teams currently use [AutoTDD](https://github.com/HPI-SWA-Teaching/AutoTDD) which is able to parse the XML from Travis builds. They will finish up their projects in a couple of weeks, so that I don't see a problem disabling XML output by default. We can then add an opt-in option. In terms of deployments, I'd also always generate an XML which then would be part of the debug artifact.
I think it's best to roll all of the above out with the new pretty printer.

**Comment by dalehenrich** [comment]
FWIW, I don't necessarily view splitting up the Metacello test runs as a bad thing ... I get the initial feedback in <10 minutes instead of 20 minutes which is not a bad thing ...

**Comment by fniephaus** [comment]
I'm not saying it's bad, cool that it works for you. I just want smalltalkCI to cover as many use cases as possible... ;)

**Comment by fniephaus** [comment]
https://github.com/hpi-swa/smalltalkCI/commit/d564587c14b2663d5e668e7e3a5c1e577c7145a1
